- id: doi:10.1038/s41534-023-00784-8
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-019-1428-4/MediaObjects/41586_2019_1428_Fig4_HTML.png?as=webp
  tags:
    - quantum gate
    - quantum computing

- id: arXiv:2402.18868
  image: https://arxiv.org/html/2402.18868v1/x1.png
  tags:
    - quantum computing
    - shelving